const blogs = [
    {
        "title": "Importance Of Houses",
        "author": "Abdullah Aziz",
        "body": "The term “shelter,” which is often used to define housing, has a strong connection to the ultimate purpose of housing throughout the world. The mental image of a shelter is of a safe, secure place that provides both privacy and protection from the elements and the temperature extremes of the outside world. This vision of shelter, however, is complex. The earthquake in Bam, Iran, before dawn on December 26, 2003, killed in excess of 30,000 people, most of whom were sleeping in their homes. Although the homes were made of the most simple construction materials, many were well over a thousand years old. Living in a home where generation after generation had been raised should provide an enormous sense of security. Nevertheless, the world press has repeatedly implied that the construction of these homes destined this disaster. The homes in Iran were constructed of sun-dried mud-brick and mudWe should think of our homes as a legacy to future generations and consider the negative environmental effects of building them to serve only one or two generations before razing or reconstructing them. Homes should be built for sustainability and for ease in future modification. We need to learn the lessons of the earthquake in Iran, as well as the 2003 heat wave in France that killed in excess of 15,000 people because of the lack of climate control systems in their homes. We must use our experience, history, and knowledge of both engineering and human health needs to construct housing that meets the need for privacy, comfort, recreation, and health maintenance.Health, home construction, and home maintenance are inseparable because of their overlapping goals. Many highly trained individuals must work together to achieve quality, safe, and healthy housing. Contractors, builders, code inspectors, housing inspectors, environmental health officers, injury control specialists, and epidemiologists all are indispensable to achieving the goal of the best housing in the world for U.S. citizens. This goal is the basis for the collaboration of the U.S. Department of Housing and Urban Development (HUD) and the Centers for Disease and Control and Prevention (CDC).",
        "id": 0,
        "img": "/blogimg1.jpg"
    },
    {
        "title": "Which house is perfect for your living",
        "author": "Murtaza Khan",
        "body": "Even if the definition of a perfect home can be very subjective, for me, a perfect home is one where I can live safely and comfortably and one that has easy access to things that we require and use normally, day on day.  Last week only I had to find a house for one of my colleague and it’s been a good learning experience for me. If you are looking for a perfect house to live in, but you are not sure how to find one easily, then read on this post. Today in this post, I am talking about all that you need to know to find a perfect home for living comfortably.But before we get in to how to find a perfect home for living, let me just take a few minutes of your time and put the things in right perspective. A home that is perfect for me may not be as perfect for you. So, it is always important to choose a home that meets your living standards, space requirements, features, and priorities. If you are happy living in it, then that’s the perfect house for you.",
        "id": 1,
        "img": "/blogimg2.jpg"
    },
    {
        "title": "Increasing Crisis of Houses in Pakistan",
        "author": "Abdullah Imdad",
        "body": "Pakistan is facing a shortage of 11-12 million residential houses and it produces issues like employment, transportation, health and education facilities. All the past governments of Pakistan seemed indifferent to providing housing facilities on a major scale to the whole country. If at all, it got any attention of the political leadership, it never moved beyond mere political slogans and things remained always the same.The urban housing shortage is estimated to be around 4 million. Pakistan’s urban population is one-third of the total population, which is expected to reach 50% by 2050.Housing or shelter is one of the basic necessities of the human being. Every person deserves the basic necessities like food education health care and shelter.Even the government employees after their service of about 30 to 35 years in scale 1-16 were not accommodated and allotted a government house. They only dreamt of having their own five Marla house in a good locality.For the last couple of decades, businessmen are hurtling towards establishing housing colonies and they have spread throughout the country. Most of these housing colonies are under private sectors and they have become a very lucrative business. The focus has tilted towards just getting maximum profit return on investment instead of providing genuine housing facilities to the masses.",
        "id": 2,
        "img": "/blogimg3.jpg"
    },
    {
        "title": "Estate Agencies and Their Roles",
        "author": "Shayan Kakkar",
        "body": "Estate agency is a fast moving industry that has evolved over the years and will continue to do so. It is drastically different now than twenty years ago, and with the current climate and ongoing uncertainty in the world, never has an estate agent been more important when selling or buying a property.Agency is an essential function of the property industry and involves the buying/renting and selling/leasing of property. Estate agents can specialise within a particular property market, such as commercial or residential real estate. The job of an estate agent contains elements of marketing, sales and administration.Real estate agencies will help you end up in an excellent location that you will appreciate. They make sure that you get to access all that you need to know about where the property they have for you is like which will come in handy in making a decision on whether you like it or not. Real estate gets people to have information on property that is on sale real fast which is helpful to buyers and investors. This way, for anyone who is looking to invest or purchase any property, they can easily do so as fast as possible.",
        "id": 3,
        "img": "/blogimg4.jpg"
    },
    {
        "title": "Online Estate Agenicies and Their worth",
        "author": "Raza Chandio",
        "body": "As mentioned above, the biggest draw is the reduction in agency fees but there are other advantages to using an online agent.The internet is a 24/7 service which means it is essentially open for business around the clock. Potential buyers are available to view your property all day and night and so you are less likely to miss out on a sale. Additionally the internet is wide reaching and so your property can be viewed all over the world at any time.The internet is a fast and easy solution for house searching. Thanks to fast broadband, buyers and sellers can be connected within milliseconds.Most buyers will tend to use Rightmove or Zoopla when they think about moving home. Unlike private listings or “do-it yourself” websites, online agencies can advertise on these sites and so you still reach thousands of potential buyers at the click of a few buttons.If you are happy to be in control of the house selling process, with more of a secondary support network from your online estate agent, who will put the house on the market, organise viewings and broker the deal, with you being the face of your property, then this is probably a great option for you.",
        "id": 4,
        "img": "/blogimg5.jpg"
    }
];
export default blogs;