export const NEW_PROJECT_REQUEST = "NEW_PROJECT_REQUEST";
export const NEW_PROJECT_SUCCESS = "NEW_PROJECT_SUCCESS";
export const NEW_PROJECT_RESET = "NEW_PROJECT_RESET";
export const NEW_PROJECT_FAIL = "NEW_PROJECT_FAIL";


export const ALL_PROJECT_REQUEST = "ALL_PROJECT_REQUEST";
export const ALL_PROJECT_SUCCESS = "ALL_PROJECT_SUCCESS";
export const ALL_PROJECT_FAIL = "ALL_PROJECT_FAIL";

export const PROJECT_DETAILS_REQUEST = "PROJECT_DETAILS_REQUEST";
export const PROJECT_DETAILS_SUCCESS = "PROJECT_DETAILS_SUCCESS";
export const PROJECT_DETAILS_FAIL = "PROJECT_DETAILS_FAIL";

// export const ADMIN_PROPERTY_REQUEST = "ADMIN_PROPERTY_REQUEST";
// export const ADMIN_PROPERTY_SUCCESS = "ADMIN_PROPERTY_SUCCESS";
// export const ADMIN_PROPERTY_FAIL = "ADMIN_PROPERTY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";