export const NEW_REGISTERATION_REQUEST = "NEW_REGISTERATION_REQUEST";
export const NEW_REGISTERATION_SUCCESS = "NEW_REGISTERATION_SUCCESS";
export const NEW_REGISTERATION_RESET = "NEW_REGISTERATION_RESET";
export const NEW_REGISTERATION_FAIL = "NEW_REGISTERATION_FAIL";

export const ALL_REGISTERATION_REQUEST = "ALL_PROPERTY_REQUEST";
export const ALL_REGISTERATION_SUCCESS = "ALL_PROPERTY_SUCCESS";
export const ALL_REGISTERATION_FAIL = "ALL_PROPERTY_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";