export const NEW_PROPERTY_REQUEST = "NEW_PROPERTY_REQUEST";
export const NEW_PROPERTY_SUCCESS = "NEW_PROPERTY_SUCCESS";
export const NEW_PROPERTY_RESET = "NEW_PROPERTY_RESET";
export const NEW_PROPERTY_FAIL = "NEW_PROPERTY_FAIL";


export const ALL_PROPERTY_REQUEST = "ALL_PROPERTY_REQUEST";
export const ALL_PROPERTY_SUCCESS = "ALL_PROPERTY_SUCCESS";
export const ALL_PROPERTY_FAIL = "ALL_PROPERTY_FAIL";

export const PROPERTY_DETAILS_REQUEST = "PROPERTY_DETAILS_REQUEST";
export const PROPERTY_DETAILS_SUCCESS = "PROPERTY_DETAILS_SUCCESS";
export const PROPERTY_DETAILS_FAIL = "PROPERTY_DETAILS_FAIL";

export const DELETE_PROPERTY_REQUEST = "DELETE_PROPERTY_REQUEST";
export const DELETE_PROPERTY_SUCCESS = "DELETE_PROPERTY_SUCCESS";
export const DELETE_PROPERTY_FAIL = "DELETE_PROPERTY_FAIL";
export const DELETE_PROPERTY_RESET = "DELETE_PROPERTY_RESET";


export const ADMIN_PROPERTY_REQUEST = "ADMIN_PROPERTY_REQUEST";
export const ADMIN_PROPERTY_SUCCESS = "ADMIN_PROPERTY_SUCCESS";
export const ADMIN_PROPERTY_FAIL = "ADMIN_PROPERTY_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";
